name: Test Install Script

on:
  push:
    branches: [ dev, master, github_ci_docker_test ]
  pull_request:
    branches: [ dev, master, github_ci_docker_test ]

jobs:
  test-install:
    strategy:
      matrix:
        ubuntu_version: [18.04, 20.04, 22.04, 24.04]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:${{ github.workspace }} \
          -w ${{ github.workspace }} \
          ubuntu:${{ matrix.ubuntu_version }} \
          bash -c "
            set -u && 
            export DEBIAN_FRONTEND=noninteractive &&
            # Set timezone to avoid tzdata interactive prompt
            ln -sf /usr/share/zoneinfo/UTC /etc/localtime &&
            apt update &&
            apt install -y locales &&
            locale-gen en_US.UTF-8 &&
            export LANG=en_US.UTF-8 &&
            export LC_ALL=en_US.UTF-8 &&
            apt update && apt install -y sudo python3 python3-pip python3-venv python3-yaml python3-distro wget &&
            python3 -m venv /tmp/test_env &&
            source /tmp/test_env/bin/activate &&
            pip install --upgrade pip  -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple&&
            pip install pyyaml distro   -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple&&
            cd tests && 
            PYTHONIOENCODING=utf-8 python3 -u test_runner.py
          "
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-ubuntu-${{ matrix.ubuntu_version }}
        path: |
          tests/test_report.json
          tests/test_report.html
        if-no-files-found: ignore
