name: Test Install Script

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-install:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-yaml python3-distro

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml distro

    - name: Run tests
      run: |
        cd tests && python3 test_runner.py